### ISSUE TITLE
Legend should correctly account for blank as "no"

### ISSUE THREAD

**Issue by mjacksonw** [RTCovid/ngamap#5]
For many of these, an absence of data is an implicit "No", but the legend gives it a different color.

<img width="1177" alt="Screen Shot 2020-04-12 at 7 59 11 AM" src="https://user-images.githubusercontent.com/69848/79068244-80227500-7c93-11ea-8d43-19c22f15dbd2.png">

**Comment by mradamcox** [comment]
Quick comment: This mostly has to do with the google sheet data: If we set everything to No, then it would work correctly. Alternatively, handling of the sheet data could automatically set "No" for empty values, but that would lead to ambiguity and not be transferable across all fields. I recommend making sure all of the empty values are filled in the Google sheet for maximum clarity/foolproofness.

**Comment by mradamcox** [comment]
I've set things up now so that an empty value is interpreted as the last in the value list. I.e. if a value list is "Yes" and "No", an empty value will be symbolized as "No".
